//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ducode.Essentials.NlPostcode.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PostcodeServiceFactsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PostcodeServiceFactsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ducode.Essentials.NlPostcode.Tests.PostcodeServiceFactsResources", typeof(PostcodeServiceFactsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;response&quot;: {
        ///		&quot;numFound&quot;: 14,
        ///		&quot;start&quot;: 0,
        ///		&quot;maxScore&quot;: 18.89388
        ///},
        ///	&quot;highlighting&quot;: {
        ///		&quot;pcd-d1aac9e08694ad7e3c2c632af5dc43dd&quot;: {
        ///			&quot;suggest&quot;: [&quot;Rijksstraatweg, &lt;b&gt;9752CA&lt;/b&gt; Haren Gn&quot;]
        ///		},
        ///		&quot;adr-f88ec3c0d1ac9adbeee1f48ed5a4691b&quot;: {
        ///			&quot;suggest&quot;: [&quot;Rijksstraatweg 217, &lt;b&gt;9752CA&lt;/b&gt; Haren Gn&quot;]
        ///		},
        ///		&quot;adr-085a48bce5ecc9c412c8b22f8a843bea&quot;: {
        ///			&quot;suggest&quot;: [&quot;Rijksstraatweg 217A, &lt;b&gt;9752CA&lt;/b&gt; Haren Gn&quot;]
        ///		},
        ///		&quot;adr-59a9f2a718bd6fb5772bc2259d5cf8ce&quot;: {
        ///			&quot;suggest&quot;: [&quot;Rijksstraatweg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DocsMissingResponse {
            get {
                return ResourceManager.GetString("DocsMissingResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {}.
        /// </summary>
        internal static string EmptyResponse {
            get {
                return ResourceManager.GetString("EmptyResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;response&quot;: {
        ///		&quot;numFound&quot;: 14,
        ///		&quot;start&quot;: 0,
        ///		&quot;maxScore&quot;: 18.89388,
        ///		&quot;docs&quot;: [{
        ///			&quot;type&quot;: &quot;adres&quot;,
        ///			&quot;weergavenaam&quot;: &quot;Rijksstraatweg 217, 9752CA Haren Gn&quot;,
        ///			&quot;id&quot;: &quot;adr-f88ec3c0d1ac9adbeee1f48ed5a4691b&quot;,
        ///			&quot;score&quot;: 12.319632
        ///		}, {
        ///			&quot;type&quot;: &quot;adres&quot;,
        ///			&quot;weergavenaam&quot;: &quot;Rijksstraatweg 217A, 9752CA Haren Gn&quot;,
        ///			&quot;id&quot;: &quot;adr-085a48bce5ecc9c412c8b22f8a843bea&quot;,
        ///			&quot;score&quot;: 12.319632
        ///		}, {
        ///			&quot;type&quot;: &quot;adres&quot;,
        ///			&quot;weergavenaam&quot;: &quot;Rijksstraatweg 219, 9752CA Haren Gn&quot;,
        ///			&quot;id&quot;: &quot;adr-59a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PostcodeMissingResponse {
            get {
                return ResourceManager.GetString("PostcodeMissingResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;response&quot;: {
        ///		&quot;numFound&quot;: 14,
        ///		&quot;start&quot;: 0,
        ///		&quot;maxScore&quot;: 18.89388,
        ///		&quot;docs&quot;: [{
        ///			&quot;type&quot;: &quot;postcode&quot;,
        ///			&quot;weergavenaam&quot;: &quot;9752CA Haren Gn&quot;,
        ///			&quot;id&quot;: &quot;pcd-d1aac9e08694ad7e3c2c632af5dc43dd&quot;,
        ///			&quot;score&quot;: 18.89388
        ///		}, {
        ///			&quot;type&quot;: &quot;adres&quot;,
        ///			&quot;weergavenaam&quot;: &quot;Rijksstraatweg 217, 9752CA Haren Gn&quot;,
        ///			&quot;id&quot;: &quot;adr-f88ec3c0d1ac9adbeee1f48ed5a4691b&quot;,
        ///			&quot;score&quot;: 12.319632
        ///		}, {
        ///			&quot;type&quot;: &quot;adres&quot;,
        ///			&quot;weergavenaam&quot;: &quot;Rijksstraatweg 217A, 9752CA Haren Gn&quot;,
        ///			&quot;id&quot;: &quot;adr-085a48bce5ecc9c412c8b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PostcodeRegexFailsResponse {
            get {
                return ResourceManager.GetString("PostcodeRegexFailsResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;response&quot;: {
        ///		&quot;numFound&quot;: 14,
        ///		&quot;start&quot;: 0,
        ///		&quot;maxScore&quot;: 18.89388,
        ///		&quot;docs&quot;: [{
        ///			&quot;type&quot;: &quot;postcode&quot;,
        ///			&quot;weergavenaam&quot;: &quot;Rijksstraatweg, 9752CA Haren Gn&quot;,
        ///			&quot;id&quot;: &quot;pcd-d1aac9e08694ad7e3c2c632af5dc43dd&quot;,
        ///			&quot;score&quot;: 18.89388
        ///		}, {
        ///			&quot;type&quot;: &quot;adres&quot;,
        ///			&quot;weergavenaam&quot;: &quot;Rijksstraatweg 217, 9752CA Haren Gn&quot;,
        ///			&quot;id&quot;: &quot;adr-f88ec3c0d1ac9adbeee1f48ed5a4691b&quot;,
        ///			&quot;score&quot;: 12.319632
        ///		}, {
        ///			&quot;type&quot;: &quot;adres&quot;,
        ///			&quot;weergavenaam&quot;: &quot;Rijksstraatweg 217A, 9752CA Haren Gn&quot;,
        ///			&quot;id&quot;: &quot;adr-085a4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SuccessResponse {
            get {
                return ResourceManager.GetString("SuccessResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;response&quot;: {
        ///		&quot;numFound&quot;: 14,
        ///		&quot;start&quot;: 0,
        ///		&quot;maxScore&quot;: 18.89388,
        ///		&quot;docs&quot;: [{
        ///			&quot;type&quot;: &quot;postcode&quot;,
        ///			&quot;weergavenaam&quot;: &quot;&quot;,
        ///			&quot;id&quot;: &quot;pcd-d1aac9e08694ad7e3c2c632af5dc43dd&quot;,
        ///			&quot;score&quot;: 18.89388
        ///		}, {
        ///			&quot;type&quot;: &quot;adres&quot;,
        ///			&quot;weergavenaam&quot;: &quot;Rijksstraatweg 217, 9752CA Haren Gn&quot;,
        ///			&quot;id&quot;: &quot;adr-f88ec3c0d1ac9adbeee1f48ed5a4691b&quot;,
        ///			&quot;score&quot;: 12.319632
        ///		}, {
        ///			&quot;type&quot;: &quot;adres&quot;,
        ///			&quot;weergavenaam&quot;: &quot;Rijksstraatweg 217A, 9752CA Haren Gn&quot;,
        ///			&quot;id&quot;: &quot;adr-085a48bce5ecc9c412c8b22f8a843bea&quot;,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WeergavenaamEmptyResponse {
            get {
                return ResourceManager.GetString("WeergavenaamEmptyResponse", resourceCulture);
            }
        }
    }
}
